package org.iesvdm.tienda.modelo;
// Generated 3 dic 2023 12:28:04 by Hibernate Tools 5.6.15.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	private int codigoCliente;
	private String nombreCliente;
	private String nombreContacto;
	private String apellidoContacto;
	private String telefono;
	private String lineaDireccion;
	private String ciudad;
	private String region;
	private String pais;
	private String codigoPostal;
	private BigDecimal limiteCredito;
	private Set pedidos = new HashSet(0);
	private Set<Pago> pagos = new HashSet<>(0);

	public Cliente() {
	}

	public Cliente(int codigoCliente, String nombreCliente, String telefono, String lineaDireccion,
			String ciudad) {
		this.codigoCliente = codigoCliente;
		this.nombreCliente = nombreCliente;
		this.telefono = telefono;
		this.lineaDireccion = lineaDireccion;
		this.ciudad = ciudad;
	}

	public Cliente(int codigoCliente, String nombreCliente, String nombreContacto,
			String apellidoContacto, String telefono, String lineaDireccion,
			String ciudad, String region, String pais, String codigoPostal, BigDecimal limiteCredito, Set pedidos,
			Set pagos) {
		this.codigoCliente = codigoCliente;
		this.nombreCliente = nombreCliente;
		this.nombreContacto = nombreContacto;
		this.apellidoContacto = apellidoContacto;
		this.telefono = telefono;
		this.lineaDireccion = lineaDireccion;
		this.ciudad = ciudad;
		this.region = region;
		this.pais = pais;
		this.codigoPostal = codigoPostal;
		this.limiteCredito = limiteCredito;
		this.pedidos = pedidos;
		this.pagos = pagos;
	}

	public int getCodigoCliente() {
		return this.codigoCliente;
	}

	public void setCodigoCliente(int codigoCliente) {
		this.codigoCliente = codigoCliente;
	}


	public String getNombreCliente() {
		return this.nombreCliente;
	}

	public void setNombreCliente(String nombreCliente) {
		this.nombreCliente = nombreCliente;
	}

	public String getNombreContacto() {
		return this.nombreContacto;
	}

	public void setNombreContacto(String nombreContacto) {
		this.nombreContacto = nombreContacto;
	}

	public String getApellidoContacto() {
		return this.apellidoContacto;
	}

	public void setApellidoContacto(String apellidoContacto) {
		this.apellidoContacto = apellidoContacto;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getLineaDireccion() {
		return this.lineaDireccion;
	}

	public void setLineaDireccion(String lineaDireccion) {
		this.lineaDireccion = lineaDireccion;
	}

	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	public String getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(String codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

	public BigDecimal getLimiteCredito() {
		return this.limiteCredito;
	}

	public void setLimiteCredito(BigDecimal limiteCredito) {
		this.limiteCredito = limiteCredito;
	}

	public Set getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set pedidos) {
		this.pedidos = pedidos;
	}

	public Set<Pago> getPagos() {
		return this.pagos;
	}

	public void setPagos(Set<Pago> pagos) {
		this.pagos = pagos;
	}

	@Override
	public String toString() {
		return "Cliente{" +
				"codigoCliente=" + codigoCliente +
				", nombreCliente='" + nombreCliente + '\'' +
				", nombreContacto='" + nombreContacto + '\'' +
				", apellidoContacto='" + apellidoContacto + '\'' +
				", telefono='" + telefono + '\'' +
				", lineaDireccion='" + lineaDireccion + '\'' +
				", ciudad='" + ciudad + '\'' +
				", region='" + region + '\'' +
				", pais='" + pais + '\'' +
				", codigoPostal='" + codigoPostal + '\'' +
				", limiteCredito=" + limiteCredito +
				'}';
	}
}
